[package]
name = "remotactoe"
version = "0.1.0"
authors = ["mattatmsft"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.12.0"
rand = "0.7.3"
indicatif = "0.15.0"